### ISSUE TITLE
Tree-Sitter queries for syntax-highlighting

### ISSUE THREAD

**Issue by d4h0** [ionide/tree-sitter-fsharp#11]
Hi,

I'm trying to add Fsharp support to [Helix](https://helix-editor.com/), and [they require](https://docs.helix-editor.com/guides/adding_languages.html#queries) tree-sitter [queries](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#queries) for syntax-highlighting.

I couldn't find anything about such queries in this repo (besides a comment in `bindings/rust/lib.rs`).

Is my assumption correct, that there are no such queries available?

If so: Is this something planned?

**Comment by Nsidorenco** [comment]
There is no such queries at the moment. They would likely be added at some point, but they are not on my timeline currently.

**Comment by vzarytovskii** [comment]
> There is no such queries at the moment. They would likely be added at some point, but they are not on my timeline currently. 

I can look into it, once the grammar stabilized.

**Comment by glyh** [comment]
Is this working at this moment?

**Comment by Nsidorenco** [comment]
The repo has contained highlight queries for quite some time now.
They are obviously not finished, but I'll close this issue in favour of more specific query related issues.
