### ISSUE TITLE
Amplifying F#

### ISSUE THREAD

**Issue by nojaf** [ionide/tree-sitter-fsharp#37]
Hello @Nsidorenco,

This is more a question than an issue/bug but I'm not sure how to reach out:

I'm part of [Amplifying F#](https://amplifyingfsharp.io/), an initiative to inspire more people to contribute to open-source F# projects.
We host [virtual sessions](https://amplifyingfsharp.io/sessions/) to learn about various topics and we are wondering if you would be interested in giving a session on how your tree-sitter project works.
It could spark enthusiasm for people to start contributing to this project!

Cheers,

Florian

**Comment by sergey-tihon** [comment]
would be very interesting to watch this session!

**Comment by Nsidorenco** [comment]
Hi @nojaf, 

Thanks for reaching out. This does sound interesting and potentially something I would like to do. 
However, I've had very limited time to work on this for quite some time now, so I won't have much to talk about until I get time to revive the project.

**Comment by nojaf** [comment]
Thanks Nikolaj, don't hesitate to reach out when the time si right.

**Comment by edgarfgp** [comment]
+1 for an AF session

**Comment by edgarfgp** [comment]
Thanks @vzarytovskii for the amazing tree-sitter presentation.  Hopefully this will help with some contributions to this project.

- [Session desc + video](https://amplifyingfsharp.io/sessions/2024/05/10/)
