### ISSUE TITLE
Move to Ionide (or fsprojects)?

### ISSUE THREAD

**Issue by sergey-tihon** [ionide/tree-sitter-fsharp#42]
Hello @Nsidorenco,

First of all, thank you for all your efforts to make tree-sitter for F# a thing.

We (as an F# community 🦔) and I (by my own) believe that this project play important role for F# support inside modern editors and we should do our best to keep it maintained.

Based on our recent discussion on X we potentially have people interested
- https://twitter.com/vzarytovskii/status/1774516075146645752
- https://twitter.com/edgarfsharp/status/1774500470729371891 

Do not you mind to contribute this project to [fsprojects](https://github.com/fsprojects) organisations?

You will preserve the admin role for repo and we will be able to add more maintainers.
If no, we probably have to fork it to make ball rolling.

Regards,
Sergey

// cc @vzarytovskii , @edgarfgp

**Comment by Nsidorenco** [comment]
Hi @sergey-tihon,

I think what you saying sounds reasonable.

My experience has been that projects like these a quite hard to get into, since it involves learning tree sitter, the F# language spec, but also a custom made c parser. Which overall makes the barrier to collaboration quite high. 
But regardless, I'd very much welcome we can get more involved in this project.

**Comment by MangelMaxime** [comment]
Hello,

I think if this projet was to move then https://github.com/ionide/ organisation is probably the better place.

Quoting them [from Twitter](https://twitter.com/IonideProject/status/1774848748855673133)

> The Ionide organization continues to be the one-stop shop for F# editor tools for any editor, any developer, and any style of work. 

cc The main admin of Ionide org

@baronfel @theangrybyrd @Krzysztof-Cieslak

**Comment by sergey-tihon** [comment]
I completely agree, that it should be under Ionide organization.

@Krzysztof-Cieslak support us as well https://twitter.com/k_cieslak/status/1774748141037777262

What is the move process?

**Comment by Krzysztof-Cieslak** [comment]
> What is the move process?

0. Make sure @Nsidorenco wants to do this - it's their choice :-) 
1. If so we will invite them to the Ionide org as a member
2. We will create `tree-sitter-admin` team in the org, and add @Nsidorenco in there as an admin of the team
3. Transfer repo
4. We will add `tree-sitter-admin` as an admins to the repo.

**Comment by Nsidorenco** [comment]
Personally, where this project lives is not that important to me.
So, if the general consensus is that the ionide org is the best place for this then by all means let us get the process started :)

**Comment by Nsidorenco** [comment]
Done :)

**Comment by baronfel** [comment]
@Nsidorenco just checking in - do the permissions and everything look all correct to you?

**Comment by Nsidorenco** [comment]
Hi @baronfel,
Yeah, everything looks good on my end. Thanks!
