### ISSUE TITLE
Type Arguments with names fail to parse

### ISSUE THREAD

**Issue by WillEhrendreich** [ionide/tree-sitter-fsharp#54]
![image](https://github.com/ionide/tree-sitter-fsharp/assets/55286472/f417a25f-6e60-4543-87b6-b9206abe3546)

Normal type arguments work like IEnumerable<int> for instance, but ones like you get for SQLProvider where you are sometimes specifying the names of the arguments are erroring out when parsed 

I don't know how to fix this, or describe it really, but the included picture shows exactly what's up. 

I Just watched the tree-sitter-fsharp Amplifying FSharp video, and it got me curious to see if I could find a problem to solve. 

Can someone help me figure out how to even start on this? lol. I watched the video but I still don't really get what I do to make an improvement here, exactly. I know I would add some rule to the grammar.js, but I don't know what to even call this, or how to add rules for parsing it, or.. well anything. but I do want to learn. 

@vzarytovskii  thank you so much for the session today.

**Comment by vzarytovskii** [comment]
The problem is in `type_abbrev_defn`, specifically its last part, it tries to parse it as
```javascript
type_abbrev_defn: $ =>
      seq(
        $.type_name,
        '=',
        scoped($.type, $._indent, $._dedent),
      ),
```
And the `scoped` part probably doesn't know how to parse something like `Type<Ident = "string">`.

`type` is declared like following:
```javascript
type: $ =>
      prec(4, choice(
        $._simple_type,
        $._generic_type,
        $._paren_type,
        $._function_type,
        $._compound_type,
        $._postfix_type,
        $._list_type,
        $._static_type,
        $.type_argument,
        $._constrained_type,
        $._flexible_type,
      )),
```

Which means it can be any of the listed definitions. It probably is missing the one with "argument". Actually I am not sure how it's called in spec. Probably it will be a matter of adding it.

**Comment by vzarytovskii** [comment]
Alternatively, `type_attributes` can be extended to support `ident = const`.

**Comment by Nsidorenco** [comment]
I think @vzarytovskii has already given some very nice pointers on this.

The way I would proceed would be to look at the `type_attribute` definition in [grammar.js](https://github.com/ionide/tree-sitter-fsharp/blob/7769a1950994a56534e2f7b483ac00bf963a0122/grammar.js#L1056).

```fsharp
    type_attribute: $ =>
      choice(
        $.type,
        // measure
        // static-parameter
      )
```

Here the `static-parameter` was taken from the spec, but never implemented:

<img width="217" alt="Screenshot 2024-05-13 at 22 25 13" src="https://github.com/ionide/tree-sitter-fsharp/assets/3179191/f96b065b-dbc3-47a7-a440-327bd28f28d7">

If you add the above definitions as nodes in the grammar, we should probably be good to go!

If you feel like it, you can experiment in a PR, and reach out if you get stuck at any point
